export const NPC_WIKI_LINKS = {
    "Abyssal demon": "https://oldschool.runescape.wiki/w/Abyssal_demon#Standard",
    "Abyssal demon (Wilderness Slayer Cave)": "https://oldschool.runescape.wiki/w/Abyssal_demon#Wilderness_Slayer_Cave",
    "Abyssal Sire": "https://oldschool.runescape.wiki/w/Abyssal_Sire",
    "Adamant dragon": "https://oldschool.runescape.wiki/w/Adamant_dragon",
    "Adventurer Jon (sharpshooter)": "https://oldschool.runescape.wiki/w/Adventurer_Jon#Sharpshooter",
    "Al Kharid warrior": "https://oldschool.runescape.wiki/w/Al_Kharid_warrior",
    "Alchemical Hydra": "https://oldschool.runescape.wiki/w/Alchemical_Hydra",
    "Ancient chest": "https://oldschool.runescape.wiki/w/Ancient_chest#Opened",
    "Ancient Wyvern": "https://oldschool.runescape.wiki/w/Ancient_Wyvern",
    "Ancient Zygomite": "https://oldschool.runescape.wiki/w/Ancient_Zygomite",
    "Angry barbarian spirit": "https://oldschool.runescape.wiki/w/Angry_barbarian_spirit",
    "Ankou": "https://oldschool.runescape.wiki/w/Ankou",
    "Ankou (Wilderness Slayer Cave)": "https://oldschool.runescape.wiki/w/Ankou#Wilderness_Slayer_Cave_drops",
    "Araxxor": "https://oldschool.runescape.wiki/w/Araxxor",
    "Araxyte": "https://oldschool.runescape.wiki/w/Tiger_shark",
    "Archer (Burthorpe)": "https://oldschool.runescape.wiki/w/Archer_(Burthorpe)",
    "Ava's accumulator": "https://oldschool.runescape.wiki/w/Ava's_accumulator",
    "Ava's assembler": "https://oldschool.runescape.wiki/w/Ava's_assembler",
    "Ava's attractor": "https://oldschool.runescape.wiki/w/Ava's_attractor",
    "Aviansie": "https://oldschool.runescape.wiki/w/Aviansie",
    "Balfrug Kreeyath": "https://oldschool.runescape.wiki/w/Balfrug_Kreeyath",
    "Barbarian Assault/Gambles (High Gambles)": "https://oldschool.runescape.wiki/w/Barbarian_Assault/Gambles#High_Gambles",
    "Barbarian Assault/Gambles (Low Gambles)": "https://oldschool.runescape.wiki/w/Barbarian_Assault/Gambles#Low_Gambles",
    "Barbarian Assault/Gambles (Medium Gambles)": "https://oldschool.runescape.wiki/w/Barbarian_Assault/Gambles#Medium_Gambles",
    "Barrel (Shaman Caves)": "https://oldschool.runescape.wiki/w/Barrel_(Shaman_Caves)",
    "Basilisk": "https://oldschool.runescape.wiki/w/Basilisk",
    "Basilisk Knight": "https://oldschool.runescape.wiki/w/Basilisk_Knight",
    "Berserk barbarian spirit": "https://oldschool.runescape.wiki/w/Berserk_barbarian_spirit",
    "Big Wolf": "https://oldschool.runescape.wiki/w/Big_Wolf",
    "Bird nest (seeds)": "https://oldschool.runescape.wiki/w/Bird_nest_(seeds)",
    "Bird nest (Wyson)": "https://oldschool.runescape.wiki/w/Bird_nest_(Wyson)",
    "Black Chest": "https://oldschool.runescape.wiki/w/Black_Chest_(red)",
    "Black demon (Wilderness Slayer Cave)": "https://oldschool.runescape.wiki/w/Black_demon#Wilderness_Slayer_Cave",
    "Black dragon": "https://oldschool.runescape.wiki/w/Black_dragon",
    "Black dragon (Wilderness Slayer Cave)": "https://oldschool.runescape.wiki/w/Black_dragon#Wilderness_Slayer_Cave",
    "Black Guard (level 25)": "https://oldschool.runescape.wiki/w/Black_Guard#Level_25",
    "Black Knight": "https://oldschool.runescape.wiki/w/Black_Knight",
    "Black Knight Titan": "https://oldschool.runescape.wiki/w/Black_Knight_Titan",
    "Blue dragon": "https://oldschool.runescape.wiki/w/Green_dragon",
    "Branda the Fire Queen": "https://oldschool.runescape.wiki/w/Branda_the_Fire_Queen",
    "Bree": "https://oldschool.runescape.wiki/w/Bree",
    "Bronze Chest": "https://oldschool.runescape.wiki/w/Bronze_Chest",
    "Bronze dragon": "https://oldschool.runescape.wiki/w/Bronze_dragon",
    "Brutal black dragon": "https://oldschool.runescape.wiki/w/Brutal_black_dragon",
    "Brutal blue dragon": "https://oldschool.runescape.wiki/w/Brutal_blue_dragon",
    "Brutal green dragon": "https://oldschool.runescape.wiki/w/Brutal_green_dragon",
    "Brutal red dragon": "https://oldschool.runescape.wiki/w/Brutal_red_dragon",
    "Bull shark": "https://oldschool.runescape.wiki/w/Bull_shark",
    "Calvar'ion": "https://oldschool.runescape.wiki/w/Calvar'ion",
    "Canifis citizens, human forms": "https://oldschool.runescape.wiki/w/Canifis_citizen#Human_forms",
    "Cannonball stall": "https://oldschool.runescape.wiki/w/Cannonball_stall",
    "Castle wars supply crate": "https://oldschool.runescape.wiki/w/Castle_wars_supply_crate",
    "Catablepon": "https://oldschool.runescape.wiki/w/Catablepon",
    "Cave horror": "https://oldschool.runescape.wiki/w/Cave_horror",
    "Cerberus": "https://oldschool.runescape.wiki/w/Cerberus",
    "Chaos druid": "https://oldschool.runescape.wiki/w/Chaos_druid",
    "Chaos druid warrior": "https://oldschool.runescape.wiki/w/Chaos_druid_warrior",
    "Chaos Elemental": "https://oldschool.runescape.wiki/w/Chaos_Elemental",
    "Chaos Fanatic": "https://oldschool.runescape.wiki/w/Chaos_Fanatic",
    "Chest (alchemist's signet)": "https://oldschool.runescape.wiki/w/Chest_(alchemist's_signet)",
    "Chest (Dorgesh-Kaan Average)": "https://oldschool.runescape.wiki/w/Chest_(Dorgesh-Kaan_Average)",
    "Chest (Maze)": "https://oldschool.runescape.wiki/w/Chest_(Maze)",
    "Chest (moon key)": "https://oldschool.runescape.wiki/w/Chest_(moon_key)",
    "Chewed bones": "https://oldschool.runescape.wiki/w/Chewed_bones",
    "Chicken": "https://oldschool.runescape.wiki/w/Chicken",
    "Chilled jelly": "https://oldschool.runescape.wiki/w/Chilled_jelly",
    "Christmas cracker": "https://oldschool.runescape.wiki/w/Christmas_cracker",
    "Cockathrice": "https://oldschool.runescape.wiki/w/Cockathrice",
    "Cockatrice": "https://oldschool.runescape.wiki/w/Cockatrice",
    "Coffin (Hallowed Sepulchre)": "https://oldschool.runescape.wiki/w/Coffin_(Hallowed_Sepulchre)",
    "Commander Zilyana": "https://oldschool.runescape.wiki/w/Commander_Zilyana",
    "Corporeal Beast": "https://oldschool.runescape.wiki/w/Corporeal_beast",
    "Crawling Hand": "https://oldschool.runescape.wiki/w/Crawling_Hand",
    "Crazy archaeologist": "https://oldschool.runescape.wiki/w/Crazy_archaeologist",
    "Crossbow stall": "https://oldschool.runescape.wiki/w/Crossbow_stall",
    "Crystal impling": "https://oldschool.runescape.wiki/w/Crystal_impling",
    "Cyclops (Ardougne Zoo)": "https://oldschool.runescape.wiki/w/Cyclops_(Ardougne_Zoo)",
    "Cyclops (Catacombs of Kourend)": "https://oldschool.runescape.wiki/w/Cyclops_(Catacombs_of_Kourend)",
    "Cyclops (God Wars Dungeon)": "https://oldschool.runescape.wiki/w/Cyclops_(God_Wars_Dungeon)",
    "Cyclops (Warriors' Guild Basement)": "https://oldschool.runescape.wiki/w/Cyclops#Warriors'_Guild_Basement",
    "Cyclops (Warriors' Guild Top Floor)": "https://oldschool.runescape.wiki/w/Cyclops#Warriors'_Guild_Top_Floor",
    "Dagannoth": "https://oldschool.runescape.wiki/w/Dagannoth",
    "Dagannoth (Waterbirth_Island) (Level 88)": "https://oldschool.runescape.wiki/w/Dagannoth_(Waterbirth_Island)#Level_88",
    "Dagannoth (Waterbirth_Island) (Level 90)": "https://oldschool.runescape.wiki/w/Dagannoth_(Waterbirth_Island)#Level_90",
    "Dagannoth Rex": "https://oldschool.runescape.wiki/w/Dagannoth_Rex",
    "Dagannoth Supreme": "https://oldschool.runescape.wiki/w/Dagannoth_Supreme",
    "Demonic gorilla": "https://oldschool.runescape.wiki/w/Tortured_gorilla",
    "Deranged archaeologist": "https://oldschool.runescape.wiki/w/Sarachnis",
    "Desert Wolf": "https://oldschool.runescape.wiki/w/Desert_Wolf",
    "Dire Wolf": "https://oldschool.runescape.wiki/w/Dire_Wolf",
    "Dire Wolf Alpha": "https://oldschool.runescape.wiki/w/Dire_Wolf_Alpha",
    "Dirty arrowtips": "https://oldschool.runescape.wiki/w/Dirty_arrowtips",
    "Disciple of Iban": "https://oldschool.runescape.wiki/w/Disciple_of_Iban",
    "Doom of Mokhaiotl": "https://oldschool.runescape.wiki/w/Doom_of_Mokhaiotl",
    "Dragon impling": "https://oldschool.runescape.wiki/w/Dragon_impling",
    "Drake": "https://oldschool.runescape.wiki/w/Drake",
    "Drink troll": "https://oldschool.runescape.wiki/w/Drink_troll",
    "Druid": "https://oldschool.runescape.wiki/w/Druid",
    "Duke Sucellus": "https://oldschool.runescape.wiki/w/Duke_Sucellus",
    "Dust devil": "https://oldschool.runescape.wiki/w/Dust_devil",
    "Dust devil (Wilderness Slayer Cave)": "https://oldschool.runescape.wiki/w/Dust_devil#Wilderness_Slayer_Cave",
    "Dwarf": "https://oldschool.runescape.wiki/w/Dwarf",
    "Eclectic impling": "https://oldschool.runescape.wiki/w/Eclectic_impling",
    "Elder Chaos druid": "https://oldschool.runescape.wiki/w/Elder_Chaos_druid",
    "Eldric the Ice King": "https://oldschool.runescape.wiki/w/Eldric_the_Ice_King",
    "Elven Crystal Chest": "https://oldschool.runescape.wiki/w/Elven_Crystal_Chest",
    "Enraged barbarian spirit": "https://oldschool.runescape.wiki/w/Enraged_barbarian_spirit",
    "Ent": "https://oldschool.runescape.wiki/w/Ent",
    "Expert potion pack": "https://oldschool.runescape.wiki/w/Expert_potion_pack",
    "Extra supply crate (Wintertodt)": "https://oldschool.runescape.wiki/w/Extra_supply_crate",
    "Ferocious barbarian spirit": "https://oldschool.runescape.wiki/w/Ferocious_barbarian_spirit",
    "Fire giant": "https://oldschool.runescape.wiki/w/Fire_giant",
    "Flight Kilisa": "https://oldschool.runescape.wiki/w/Flight_Kilisa",
    "Flockleader Geerin": "https://oldschool.runescape.wiki/w/Flockleader Geerin",
    "Forgotten Lockbox": "https://oldschool.runescape.wiki/w/Forgotten_lockbox",
    "Forgotten Soul": "https://oldschool.runescape.wiki/w/Forgotten_Soul",
    "Former Vampyre": "https://oldschool.runescape.wiki/w/Former_Vampyre",
    "Gargoyle": "https://oldschool.runescape.wiki/w/Gargoyle",
    "Giant Mole": "https://oldschool.runescape.wiki/w/Zulrah",
    "Giant rockslug": "https://oldschool.runescape.wiki/w/Giant_rockslug",
    "Giant Sea Snake": "https://oldschool.runescape.wiki/w/Giant_Sea_Snake",
    "Gnome Restaurant Tips": "https://oldschool.runescape.wiki/w/King_Bolren#Gnome_Restaurant_Tips",
    "Goblin": "https://oldschool.runescape.wiki/w/Goblin",
    "Gold Chest": "https://oldschool.runescape.wiki/w/Gold_Chest_(red)",
    "Gorak": "https://oldschool.runescape.wiki/w/Gorak",
    "Grand Hallowed Coffin": "https://oldschool.runescape.wiki/w/Grand_Hallowed_Coffin",
    "Great white shark": "https://oldschool.runescape.wiki/w/Great_white_shark",
    "Greater abyssal demon": "https://oldschool.runescape.wiki/w/Greater_abyssal_demon",
    "Greater demon (Wilderness Slayer Cave)": "https://oldschool.runescape.wiki/w/Greater_demon#Wilderness_Slayer_Cave_drops",
    "Greater Nechryael": "https://oldschool.runescape.wiki/w/Greater_Nechryael",
    "Green dragon": "https://oldschool.runescape.wiki/w/Green_dragon",
    "Green dragon (Wilderness Slayer Cave)": "https://oldschool.runescape.wiki/w/Green_dragon#Wilderness_Slayer_Cave",
    "Grimy Lizard": "https://oldschool.runescape.wiki/w/Grimy_Lizard",
    "Grotesque Guardians": "https://oldschool.runescape.wiki/w/Grotesque_Guardians",
    "Growler": "https://oldschool.runescape.wiki/w/Growler",
    "Gryphon": "https://oldschool.runescape.wiki/w/Gryphon",
    "Guard": "https://oldschool.runescape.wiki/w/Guard",
    "Guard (H.A.M. Storerooms)": "https://oldschool.runescape.wiki/w/Guard_(H.A.M._Storerooms)",
    "H.A.M. Guard": "https://oldschool.runescape.wiki/w/H.A.M._Guard",
    "H.A.M. Member": "https://oldschool.runescape.wiki/w/H.A.M._Member",
    "Hallowed sack": "https://oldschool.runescape.wiki/w/Hallowed_sack",
    "Hespori": "https://oldschool.runescape.wiki/w/Hespori",
    "Highwayman": "https://oldschool.runescape.wiki/w/Highwayman",
    "Hill Giant": "https://oldschool.runescape.wiki/w/Hill_Giant",
    "Hobgoblin": "https://oldschool.runescape.wiki/w/Hobgoblin",
    "Hunters' loot sack": "https://oldschool.runescape.wiki/w/Hunters'_loot_sack",
    "Ice Giant": "https://oldschool.runescape.wiki/w/Ice_giant",
    "Ice Giant (Wilderness Slayer Cave)": "https://oldschool.runescape.wiki/w/Ice_giant#Wilderness_Slayer_Cave_drops",
    "Ice warrior": "https://oldschool.runescape.wiki/w/Ice_warrior",
    "Ice wolf": "https://oldschool.runescape.wiki/w/Ice_wolf",
    "Imp": "https://oldschool.runescape.wiki/w/Imp",
    "Iron dragon": "https://oldschool.runescape.wiki/w/Iron_dragon",
    "Jelly (Wilderness Slayer Cave)": "https://oldschool.runescape.wiki/w/Jelly#Wilderness_Slayer_Cave",
    "Jungle Wolf": "https://oldschool.runescape.wiki/w/Jungle_Wolf",
    "K'ril Tsutsaroth": "https://oldschool.runescape.wiki/w/K'ril_Tsutsaroth",
    "Kalphite Guardian": "https://oldschool.runescape.wiki/w/Kalphite_Guardian",
    "Kalphite Queen": "https://oldschool.runescape.wiki/w/Kalphite_Queen",
    "Kalphite Worker": "https://oldschool.runescape.wiki/w/Kalphite_Worker",
    "King Black Dragon": "https://oldschool.runescape.wiki/w/King_Black_Dragon",
    "Kree'arra": "https://oldschool.runescape.wiki/w/Kree'arra",
    "Large salvage": "https://oldschool.runescape.wiki/w/Large_salvage",
    "Lava dragon": "https://oldschool.runescape.wiki/w/Lava_dragon",
    "Lava Strykewyrm": "https://oldschool.runescape.wiki/w/Lava_Strykewyrm",
    "Lesser demon (Wilderness Slayer Cave)": "https://oldschool.runescape.wiki/w/Lesser_demon#Wilderness_Slayer_Cave_drops",
    "Lizardman brute": "https://oldschool.runescape.wiki/w/Lizardman_brute",
    "Lizardman Level 53": "https://oldschool.runescape.wiki/w/Lizardman#Level_53",
    "Lizardman Level 62": "https://oldschool.runescape.wiki/w/Lizardman#Level_62",
    "Lizardman shaman": "https://oldschool.runescape.wiki/w/Lizardman_shaman",
    "Locust rider": "https://oldschool.runescape.wiki/w/Locust_rider",
    "Long-tailed Wyvern": "https://oldschool.runescape.wiki/w/Long-tailed_Wyvern",
    "Lost camphor crate": "https://oldschool.runescape.wiki/w/Lost_camphor_crate",
    "Lost ironwood crate": "https://oldschool.runescape.wiki/w/Lost_ironwood_crate",
    "Lost mahogany crate": "https://oldschool.runescape.wiki/w/Lost_mahogany_crate",
    "Lost oak crate": "https://oldschool.runescape.wiki/w/Lost_oak_crate",
    "Lost wooden crate": "https://oldschool.runescape.wiki/w/Lost_wooden_crate",
    "Lunar Chest": "https://oldschool.runescape.wiki/w/Lunar_Chest",
    "Magic axe": "https://oldschool.runescape.wiki/w/Magic_axe",
    "Magpie impling": "https://oldschool.runescape.wiki/w/Magpie_impling",
    "Mammoth": "https://oldschool.runescape.wiki/w/Mammoth",
    "Man": "https://oldschool.runescape.wiki/w/Man",
    "Maniacal monkey": "https://oldschool.runescape.wiki/w/Maniacal_monkey",
    "Maniacal Monkey Archer": "https://oldschool.runescape.wiki/w/Maniacal_Monkey_Archer",
    "Manta ray (monster)": "https://oldschool.runescape.wiki/w/Manta_ray_(monster)",
    "Martial salvage": "https://oldschool.runescape.wiki/w/Martial_salvage",
    "Master Farmer": "https://oldschool.runescape.wiki/w/Master_Farmer",
    "Minotaur": "https://oldschool.runescape.wiki/w/Minotaur",
    "Mithril dragon": "https://oldschool.runescape.wiki/w/Mithril_dragon",
    "Monk of Zamorak": "https://oldschool.runescape.wiki/w/Monk_of_Zamorak",
    "Monumental chest": "https://oldschool.runescape.wiki/w/Monumental_chest",
    "Moonlight Cockatrice": "https://oldschool.runescape.wiki/w/Moonlight_Cockatrice",
    "Moss giant": "https://oldschool.runescape.wiki/w/Moss_giant",
    "Mugger": "https://oldschool.runescape.wiki/w/Mugger",
    "Mutated Bloodveld": "https://oldschool.runescape.wiki/w/Mutated_Bloodveld",
    "Narwhal": "https://oldschool.runescape.wiki/w/Narwhal",
    "Nechryarch": "https://oldschool.runescape.wiki/w/Nechryarch#Greater",
    "Necromancer": "https://oldschool.runescape.wiki/w/Necromancer",
    "Nex": "https://oldschool.runescape.wiki/w/Nex",
    "Ninja impling": "https://oldschool.runescape.wiki/w/Ninja_impling",
    "Obor (Members)": "https://oldschool.runescape.wiki/w/Obor#Members",
    "Ocean Man": "https://oldschool.runescape.wiki/w/Ocean_Man",
    "Ogre Coffin": "https://oldschool.runescape.wiki/w/Ogre_Coffin",
    "Ogress Shaman": "https://oldschool.runescape.wiki/w/Ogress_Shaman",
    "Ogress Warrior": "https://oldschool.runescape.wiki/w/Ogress_Warrior",
    "Orca": "https://oldschool.runescape.wiki/w/Orca",
    "Ork": "https://oldschool.runescape.wiki/w/Ork",
    "Phantom Muspah": "https://oldschool.runescape.wiki/w/Phantom_Muspah",
    "Phosani's Nightmare": "https://oldschool.runescape.wiki/w/Phosani's_Nightmare",
    "Pirate": "https://oldschool.runescape.wiki/w/Pirate",
    "Plundered salvage": "https://oldschool.runescape.wiki/w/Plundered_salvage",
    "Pygmy kraken": "https://oldschool.runescape.wiki/w/Pygmy_kraken",
    "Red dragon": "https://oldschool.runescape.wiki/w/Red_dragon",
    "Reinforced chest": "https://oldschool.runescape.wiki/w/Reinforced_chest",
    "Revenants": "https://oldschool.runescape.wiki/w/Revenants",
    "Reward Cart (Wintertodt)": "https://oldschool.runescape.wiki/w/Reward_Cart",
    "Reward casket (beginner)": "https://oldschool.runescape.wiki/w/Reward_casket_(beginner)",
    "Reward casket (easy)": "https://oldschool.runescape.wiki/w/Reward_casket_(easy)",
    "Reward casket (elite)": "https://oldschool.runescape.wiki/w/Reward_casket_(elite)",
    "Reward casket (hard)": "https://oldschool.runescape.wiki/w/Reward_casket_(hard)",
    "Reward casket (master)": "https://oldschool.runescape.wiki/w/Reward_casket_(master)",
    "Reward casket (medium)": "https://oldschool.runescape.wiki/w/Reward_casket_(medium)",
    "Reward Chest (Fortis Colosseum)": "https://oldschool.runescape.wiki/w/Rewards_Chest_(Fortis_Colosseum)",
    "Reward Chest (The Gauntlet)": "https://oldschool.runescape.wiki/w/Reward_Chest_(The_Gauntlet)",
    "Rewards Guardian": "https://oldschool.runescape.wiki/w/Rewards_Guardian",
    "Rock lobster": "https://oldschool.runescape.wiki/w/Rock_lobster",
    "Rogue": "https://oldschool.runescape.wiki/w/Rogue",
    "Rune dragon": "https://oldschool.runescape.wiki/w/Rune_dragon",
    "Rusty chest": "https://oldschool.runescape.wiki/w/Rusty_chest",
    "Salarin the twisted": "https://oldschool.runescape.wiki/w/Salarin_the_twisted",
    "Sarachnis": "https://oldschool.runescape.wiki/w/Sarachnis",
    "SarArtioachnis": "https://oldschool.runescape.wiki/w/Artio",
    "Scarab Mage": "https://oldschool.runescape.wiki/w/Scarab_Mage",
    "Sea Snake Hatchling": "https://oldschool.runescape.wiki/w/Sea_Snake_Hatchling",
    "Sea Snake Young": "https://oldschool.runescape.wiki/w/Sea_Snake_Young",
    "Seed Pack": "https://oldschool.runescape.wiki/w/Seed_pack#Low_seed",
    "Seed pack": "https://oldschool.runescape.wiki/w/Seed_pack#High_seed",
    "Seed Stall": "https://oldschool.runescape.wiki/w/Seed_Stall",
    "Sergeant (Shayzien)": "https://oldschool.runescape.wiki/w/Sergeant_(Shayzien)",
    "Sergeant Grimspike": "https://oldschool.runescape.wiki/w/Sergeant_Grimspike",
    "Sergeant Steelwill": "https://oldschool.runescape.wiki/w/Sergeant_Steelwill",
    "Sergeant Strongstack": "https://oldschool.runescape.wiki/w/Sergeant_Strongstack",
    "Serum 208": "https://oldschool.runescape.wiki/w/Serum_208#4_dose",
    "Shadow warrior": "https://oldschool.runescape.wiki/w/Shadow_warrior",
    "Shadow Wyrm": "https://oldschool.runescape.wiki/w/Shadow_Wyrm",
    "Shellbane Gryphon": "https://oldschool.runescape.wiki/w/Shellbane_gryphon",
    "Silver Chest": "https://oldschool.runescape.wiki/w/Silver_Chest_(red)",
    "Skeletal wyvern": "https://oldschool.runescape.wiki/w/Skeletal_Wyvern",
    "Skeletal Wyvern": "https://oldschool.runescape.wiki/w/Skeletal_Wyvern",
    "Skeleton (Lucien's camp)": "https://oldschool.runescape.wiki/w/Skeleton_(Lucien's_camp)",
    "Skeleton (Shayzien Crypts)": "https://oldschool.runescape.wiki/w/Skeleton_(Shayzien_Crypts)",
    "Skeleton (Tarn's Lair)": "https://oldschool.runescape.wiki/w/Skeleton_(Tarn's_Lair)",
    "Skeleton brute": "https://oldschool.runescape.wiki/w/Skeleton_brute",
    "Skeleton heavy": "https://oldschool.runescape.wiki/w/Skeleton_heavy",
    "Skeleton hero": "https://oldschool.runescape.wiki/w/Skeleton_hero",
    "Skeleton thug": "https://oldschool.runescape.wiki/w/Skeleton_thug",
    "Skeleton warlord": "https://oldschool.runescape.wiki/w/Skeleton_warlord",
    "Skogre": "https://oldschool.runescape.wiki/w/Skogre",
    "Small salvage": "https://oldschool.runescape.wiki/w/Small_salvage",
    "Smoke devil": "https://oldschool.runescape.wiki/w/Smoke_devil",
    "Soldier (Burthorpe)": "https://oldschool.runescape.wiki/w/Soldier_(Burthorpe)",
    "Spined kraken": "https://oldschool.runescape.wiki/w/Spined_kraken",
    "Spiritual ranger": "https://oldschool.runescape.wiki/w/Spiritual_ranger",
    "Spiritual warrior": "https://oldschool.runescape.wiki/w/Spiritual_warrior",
    "Spitting Wyvern": "https://oldschool.runescape.wiki/w/Spitting_Wyvern",
    "Spoils of war": "https://oldschool.runescape.wiki/w/Spoils_of_war",
    "Starlight": "https://oldschool.runescape.wiki/w/Starlight",
    "Steel Chest": "https://oldschool.runescape.wiki/w/Steel_chest",
    "Steel dragon": "https://oldschool.runescape.wiki/w/Steel_dragon",
    "Stone chest": "https://oldschool.runescape.wiki/w/Stone_chest",
    "Storage crate": "https://oldschool.runescape.wiki/w/Storage_crate",
    "Strange shrine": "https://oldschool.runescape.wiki/w/Strange_shrine",
    "Sulphur Lizard": "https://oldschool.runescape.wiki/w/Sulphur_Lizard",
    "Swamp Crab": "https://oldschool.runescape.wiki/w/Swamp_Crab",
    "Taloned Wyvern": "https://oldschool.runescape.wiki/w/Taloned_Wyvern",
    "Tarnished chest": "https://oldschool.runescape.wiki/w/Tarnished_chest",
    "Temple spider": "https://oldschool.runescape.wiki/w/Temple_spider",
    "The Hueycoatl": "https://oldschool.runescape.wiki/w/The_Hueycoatl",
    "The Mimic": "https://oldschool.runescape.wiki/w/The_Mimic",
    "The Mimic (elite)": "https://oldschool.runescape.wiki/w/The_Mimic#Elite",
    "The Mimic (master)": "https://oldschool.runescape.wiki/w/The_Mimic#Master",
    "The Nightmare": "https://oldschool.runescape.wiki/w/The_Nightmare",
    "Thermonuclear smoke devil": "https://oldschool.runescape.wiki/w/Thermonuclear_smoke_devil",
    "Thief": "https://oldschool.runescape.wiki/w/Thief",
    "Tiger shark": "https://oldschool.runescape.wiki/w/Tiger_shark",
    "Tormented Demon": "https://oldschool.runescape.wiki/w/Tormented_Demon",
    "Tortoise": "https://oldschool.runescape.wiki/w/Tortoise#No_riders",
    "Tortoise (No riders)": "https://oldschool.runescape.wiki/w/Tortoise#No_riders",
    "Tortoise (With riders)": "https://oldschool.runescape.wiki/w/Tortoise#With_riders",
    "Tortured gorilla": "https://oldschool.runescape.wiki/w/Demonic_gorilla",
    "Tree spirit": "https://oldschool.runescape.wiki/w/Tree_spirit",
    "Tribesman": "https://oldschool.runescape.wiki/w/Tribesman",
    "Tribeswoman": "https://oldschool.runescape.wiki/w/Tribeswoman",
    "Tstanon Karlak": "https://oldschool.runescape.wiki/w/Tstanon_Karlak",
    "Tstanon Kerlak": "https://oldschool.runescape.wiki/w/Tstanon_Kerlak",
    "Turoth": "https://oldschool.runescape.wiki/w/Turoth",
    "Undead Druid": "https://oldschool.runescape.wiki/w/Undead_Druid",
    "Unsired": "https://oldschool.runescape.wiki/w/Unsired",
    "Vale offerings": "https://oldschool.runescape.wiki/w/Vale_offerings#Level_90+",
    "Vampyre Juvinate": "https://oldschool.runescape.wiki/w/Vampyre_Juvinate",
    "Venenatis": "https://oldschool.runescape.wiki/w/Venenatis",
    "Vet'ion": "https://oldschool.runescape.wiki/w/Vet'ion",
    "Void Knights' Reward Options (Seed pack)": "https://oldschool.runescape.wiki/w/Void_Knights'_Reward_Options#Seed_pack",
    "Vorkath": "https://oldschool.runescape.wiki/w/Vorkath#Post-quest",
    "Vyrewatch": "https://oldschool.runescape.wiki/w/Vyrewatch",
    "Vyrewatch Sentinel": "https://oldschool.runescape.wiki/w/Vyrewatch_Sentinel",
    "Wallasaki": "https://oldschool.runescape.wiki/w/Wallasaki",
    "Warped Jelly": "https://oldschool.runescape.wiki/w/Warped_Jelly",
    "Waterfiend": "https://oldschool.runescape.wiki/w/Waterfiend",
    "Werewolf": "https://oldschool.runescape.wiki/w/Werewolf",
    "White wolf": "https://oldschool.runescape.wiki/w/White_wolf",
    "Wingman Skree": "https://oldschool.runescape.wiki/w/Wingman_Skree",
    "Wise Old Man tasks": "https://oldschool.runescape.wiki/w/Wise_Old_Man_tasks",
    "Wolf": "https://oldschool.runescape.wiki/w/Wolf",
    "Woman": "https://oldschool.runescape.wiki/w/Woman",
    "Wyrm": "https://oldschool.runescape.wiki/w/Wyrm",
    "Wyrmling": "https://oldschool.runescape.wiki/w/Wyrmling",
    "Yak": "https://oldschool.runescape.wiki/w/Yak",
    "Yama": "https://oldschool.runescape.wiki/w/Yama",
    "Young impling": "https://oldschool.runescape.wiki/w/Young_impling",
    "Zakl'n Gritch": "https://oldschool.runescape.wiki/w/Zakl'n_Gritch",
    "Zalcano": "https://oldschool.runescape.wiki/w/Zalcano",
    "Zamorak ranger": "https://oldschool.runescape.wiki/w/Zamorak_ranger",
    "Zamorak warrior": "https://oldschool.runescape.wiki/w/Zamorak_warrior",
    "Zamorak wizard": "https://oldschool.runescape.wiki/w/Zamorak_wizard",
    "Zogre": "https://oldschool.runescape.wiki/w/Zogre",
    "Zombie": "https://oldschool.runescape.wiki/w/Zombie#Level_13",
    "Zombie (Level 13)": "https://oldschool.runescape.wiki/w/Zombie#Level_13",
    "Zombie (Shayzien Crypts)": "https://oldschool.runescape.wiki/w/Zombie_(Shayzien_Crypts)",
    "Zombie (Stronghold of Security)": "https://oldschool.runescape.wiki/w/Zombie_(Stronghold_of_Security)",
    "Zombie (Tarn's Lair)": "https://oldschool.runescape.wiki/w/Zombie_(Tarn's_Lair)#Medium_level",
    "Zombie pirate": "https://oldschool.runescape.wiki/w/Zombie_pirate",
    "Zombie pirate (Harmony Island)": "https://oldschool.runescape.wiki/w/Zombie_pirate_(Harmony_Island)",
    "Zombie Pirate's Locker": "https://oldschool.runescape.wiki/w/Zombie_Pirate's_Locker",
    "Zulrah": "https://oldschool.runescape.wiki/w/Zulrah"
};
